# common/config/databases/sql_config.yaml
test: #环境
  payok: #项目
    ip: '192.168.0.227'
    port: 3306
    user: 'WAYANGPAY'
    password: 'Z43@Mon88'
    db_name: 'aesygo_test'
    tables:
      platform_operator: 'operator'
      merchant_operator: 'merchant_operator'
      sales_operator: 'sales_operator'

  paylabs:
    ip: '192.168.0.233'
    port: 3306
    user: 'paylabs_payapi'
    password: 'SharkZ@DBA666'
    db_name: 'paylabs'
    tables:
      platform_operator: 'operator'
      merchant_operator: 'merchant_operator'
      sales_operator: 'sales_operator'

  tax:
    ip: '192.168.0.50'
    port: 3306
    user: 'belitax_test'
    password: 'VSwE8zVrfuUP#HN'
    db_name: 'balitax'
    tables:
      agent_base_info: 'agent_base_info'
      agent_operator: 'agent_operator'
      merchant_info: 'merchant_info'
      tax_operator: 'tax_operator'
      declaration_order: 'declaration_order'
